name: Build new version

on:
  release:
    types:
      - prereleased

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          echo "Olá mundo PRERELEASED"
